# Generated by Django 4.0.6 on 2022-08-27 10:08

import Pressure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureSensor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Label', models.CharField(max_length=100, validators=[Pressure.models.PressureSensor.validate_label])),
                ('InstallationDate', models.DateTimeField(auto_now_add=True)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('serial_number', models.CharField(default=Pressure.models.PressureSensor.compute_default, editable=False, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressureReading',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('SensorId', models.ManyToManyField(to='Pressure.pressuresensor')),
            ],
        ),
    ]
