# Generated by Django 4.0.6 on 2022-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureReading',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
                ('Value', models.DecimalField(decimal_places=3, max_digits=3)),
                ('SensorId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PressureSensor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Label', models.CharField(max_length=100)),
                ('InstallationDate', models.DateTimeField()),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
