# Generated by Django 4.0.6 on 2022-08-27 10:17

from django.db import migrations, models
from django.db.models import F

def migrate_raw_value(apps, schema):
    PressureReading = apps.get_model("Pressure","PressureReading")
    PressureReading.objects.all().update(
    raw_value=F('Value'))

class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '00001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurereading',
            name='raw_value',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
           migrations.RunPython(migrate_raw_value),
         migrations.AlterField(
            model_name='pressurereading',
            name='raw_value',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),

    ]
