# Generated by Django 4.0.6 on 2022-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='Value',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
