# Generated by Django 4.0.6 on 2022-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '0002_alter_pressurereading_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pressuresensor',
            name='InstallationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
