# Generated by Django 4.0.6 on 2022-07-23 09:46

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '0004_alter_pressurereading_sensorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='SensorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.AutoField, to='Pressure.pressuresensor'),
        ),
    ]
