# Generated by Django 4.0.6 on 2022-07-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '0007_alter_pressurereading_sensorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressurereading',
            name='SensorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pressure.pressuresensor'),
        ),
    ]
