# Generated by Django 4.0.6 on 2022-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '0008_alter_pressurereading_sensorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresensor',
            name='serial_number',
            field=models.CharField(default='456738', max_length=100),
        ),
    ]
