# Generated by Django 4.0.6 on 2022-07-27 10:53

import Pressure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '0010_alter_pressuresensor_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuresensor',
            name='Label',
            field=models.CharField(max_length=100, validators=[Pressure.models.PressureSensor.validate_label]),
        ),
    ]
