# Generated by Django 4.0.6 on 2022-08-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pressure', '0014_alter_pressuresensor_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressurereading',
            name='SensorId',
        ),
        migrations.AddField(
            model_name='pressurereading',
            name='SensorId',
            field=models.ManyToManyField(to='Pressure.pressuresensor'),
        ),
    ]
