# Generated by Django 4.0.6 on 2022-08-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fl_tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='votes',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.SlugField(default=1),
        ),
        migrations.AlterField(
            model_name='tags',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['content_type', 'object_id'], name='fl_tags_tag_content_9fe444_idx'),
        ),
    ]
