# Generated by Django 4.0.6 on 2022-08-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fl_tags', '0002_remove_tags_choice_text_remove_tags_votes_tags_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsConfigRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='tags',
            name='fl_tags_tag_content_9fe444_idx',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='object_id',
        ),
        migrations.AddField(
            model_name='tagsconfigrelation',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tagsconfigrelation',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fl_tags.tags'),
        ),
    ]
